#! /usr/bin/php
<?php
include 'engines.php';
include 'cli.php';
$config = include 'config.php';

if (isset($argv[1])) {
	if ($argv[1] == '-set') {
		$settings = array();
		for ($i = 2; $i < count($argv); $i++) {
			if (($argv[$i] == 'browser') || ($argv[$i] == 'engine')) {
				if (!isset($argv[$i + 1])) die("Missing argument for paramater " . $argv[$i]);
				$config[$argv[$i]] = $argv[$i + 1];
				$settings[$argv[$i]] = $argv[$i + 1];
			}
		}
		file_put_contents('config.php', '<?php return ' . var_export($config, true) . ';');
		echo "Saved new settings:\n";
		foreach ($settings as $key => $value) {
			echo "\t{$key} => {$value}\n";
		}
		die;
	} else if (($argv[1] == '-h') || ($argv[1] == '-help')) {
		echo "Usage:\n";
		echo "\tsopen 'search string'\t\t\t\t\t\t\t\tsearch  for 'search string'\n";
		echo "\t\tsearch string must be enclosed in quotes if it contains spaces\n\n";
		echo "\tsopen -set [param value]\n";
		echo "\t\t[browser 'default-browser']\t\t\t\t\t\tset default browser\n";
		echo "\t\t[engine 'default-engine']\t\t\t\t\t\tset default search-engine\n";
		echo "\t\tmultiple paramaters may be specified at once\n\n";
		echo "\tsopen -h or sopen -help\t\t\t\t\t\t\t\tDisplay this dialog\n";
		die;
	} else {
		$word = $argv[1];
	}
} else {
	$word = trim(fgets(STDIN));
}
$cli = new MockSearchCli;

$url = $cli->startSearch($word);
shell_exec($config['browser'] . " " . $url);
